/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.liferay.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Pessoa service. Represents a row in the &quot;pessoa&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.liferay.test.model.impl.PessoaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.liferay.test.model.impl.PessoaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Pessoa
 * @generated
 */
@ProviderType
public interface PessoaModel extends BaseModel<Pessoa> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pessoa model instance should use the {@link Pessoa} interface instead.
	 */

	/**
	 * Returns the primary key of this pessoa.
	 *
	 * @return the primary key of this pessoa
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pessoa.
	 *
	 * @param primaryKey the primary key of this pessoa
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the name of this pessoa.
	 *
	 * @return the name of this pessoa
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this pessoa.
	 *
	 * @param name the name of this pessoa
	 */
	public void setName(String name);

	/**
	 * Returns the data_nascimento of this pessoa.
	 *
	 * @return the data_nascimento of this pessoa
	 */
	public Date getData_nascimento();

	/**
	 * Sets the data_nascimento of this pessoa.
	 *
	 * @param data_nascimento the data_nascimento of this pessoa
	 */
	public void setData_nascimento(Date data_nascimento);

	/**
	 * Returns the rg of this pessoa.
	 *
	 * @return the rg of this pessoa
	 */
	@AutoEscape
	public String getRg();

	/**
	 * Sets the rg of this pessoa.
	 *
	 * @param rg the rg of this pessoa
	 */
	public void setRg(String rg);

	/**
	 * Returns the data_expedicao_rg of this pessoa.
	 *
	 * @return the data_expedicao_rg of this pessoa
	 */
	public Date getData_expedicao_rg();

	/**
	 * Sets the data_expedicao_rg of this pessoa.
	 *
	 * @param data_expedicao_rg the data_expedicao_rg of this pessoa
	 */
	public void setData_expedicao_rg(Date data_expedicao_rg);

	/**
	 * Returns the cpf of this pessoa.
	 *
	 * @return the cpf of this pessoa
	 */
	@AutoEscape
	public String getCpf();

	/**
	 * Sets the cpf of this pessoa.
	 *
	 * @param cpf the cpf of this pessoa
	 */
	public void setCpf(String cpf);

	/**
	 * Returns the nome_pai of this pessoa.
	 *
	 * @return the nome_pai of this pessoa
	 */
	@AutoEscape
	public String getNome_pai();

	/**
	 * Sets the nome_pai of this pessoa.
	 *
	 * @param nome_pai the nome_pai of this pessoa
	 */
	public void setNome_pai(String nome_pai);

	/**
	 * Returns the nome_mae of this pessoa.
	 *
	 * @return the nome_mae of this pessoa
	 */
	@AutoEscape
	public String getNome_mae();

	/**
	 * Sets the nome_mae of this pessoa.
	 *
	 * @param nome_mae the nome_mae of this pessoa
	 */
	public void setNome_mae(String nome_mae);

	/**
	 * Returns the naturalidade of this pessoa.
	 *
	 * @return the naturalidade of this pessoa
	 */
	@AutoEscape
	public String getNaturalidade();

	/**
	 * Sets the naturalidade of this pessoa.
	 *
	 * @param naturalidade the naturalidade of this pessoa
	 */
	public void setNaturalidade(String naturalidade);

	/**
	 * Returns the uf of this pessoa.
	 *
	 * @return the uf of this pessoa
	 */
	@AutoEscape
	public String getUf();

	/**
	 * Sets the uf of this pessoa.
	 *
	 * @param uf the uf of this pessoa
	 */
	public void setUf(String uf);

	/**
	 * Returns the ID of this pessoa.
	 *
	 * @return the ID of this pessoa
	 */
	public long getId();

	/**
	 * Sets the ID of this pessoa.
	 *
	 * @param id the ID of this pessoa
	 */
	public void setId(long id);

	/**
	 * Returns the plano_id of this pessoa.
	 *
	 * @return the plano_id of this pessoa
	 */
	public long getPlano_id();

	/**
	 * Sets the plano_id of this pessoa.
	 *
	 * @param plano_id the plano_id of this pessoa
	 */
	public void setPlano_id(long plano_id);

}