/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.liferay.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PlanoSaude service. Represents a row in the &quot;PlanoSaude&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.liferay.test.model.impl.PlanoSaudeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.liferay.test.model.impl.PlanoSaudeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlanoSaude
 * @generated
 */
@ProviderType
public interface PlanoSaudeModel extends BaseModel<PlanoSaude> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a plano saude model instance should use the {@link PlanoSaude} interface instead.
	 */

	/**
	 * Returns the primary key of this plano saude.
	 *
	 * @return the primary key of this plano saude
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this plano saude.
	 *
	 * @param primaryKey the primary key of this plano saude
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the plano_id of this plano saude.
	 *
	 * @return the plano_id of this plano saude
	 */
	public long getPlano_id();

	/**
	 * Sets the plano_id of this plano saude.
	 *
	 * @param plano_id the plano_id of this plano saude
	 */
	public void setPlano_id(long plano_id);

	/**
	 * Returns the descricao of this plano saude.
	 *
	 * @return the descricao of this plano saude
	 */
	@AutoEscape
	public String getDescricao();

	/**
	 * Sets the descricao of this plano saude.
	 *
	 * @param descricao the descricao of this plano saude
	 */
	public void setDescricao(String descricao);

}