/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.liferay.test.model.impl;

import br.com.liferay.test.model.PlanoSaude;
import br.com.liferay.test.model.PlanoSaudeModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the PlanoSaude service. Represents a row in the &quot;PlanoSaude&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>PlanoSaudeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PlanoSaudeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlanoSaudeImpl
 * @generated
 */
@ProviderType
public class PlanoSaudeModelImpl
	extends BaseModelImpl<PlanoSaude> implements PlanoSaudeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a plano saude model instance should use the <code>PlanoSaude</code> interface instead.
	 */
	public static final String TABLE_NAME = "PlanoSaude";

	public static final Object[][] TABLE_COLUMNS = {
		{"plano_id", Types.BIGINT}, {"descricao", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("plano_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("descricao", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PlanoSaude (plano_id LONG not null primary key,descricao VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table PlanoSaude";

	public static final String ORDER_BY_JPQL =
		" ORDER BY planoSaude.plano_id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PlanoSaude.plano_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long DESCRICAO_COLUMN_BITMASK = 1L;

	public static final long PLANO_ID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public PlanoSaudeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _plano_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPlano_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _plano_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PlanoSaude.class;
	}

	@Override
	public String getModelClassName() {
		return PlanoSaude.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PlanoSaude, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PlanoSaude, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PlanoSaude, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((PlanoSaude)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PlanoSaude, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PlanoSaude, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PlanoSaude)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PlanoSaude, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PlanoSaude, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PlanoSaude>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PlanoSaude.class.getClassLoader(), PlanoSaude.class,
			ModelWrapper.class);

		try {
			Constructor<PlanoSaude> constructor =
				(Constructor<PlanoSaude>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<PlanoSaude, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PlanoSaude, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PlanoSaude, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<PlanoSaude, Object>>();
		Map<String, BiConsumer<PlanoSaude, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<PlanoSaude, ?>>();

		attributeGetterFunctions.put("plano_id", PlanoSaude::getPlano_id);
		attributeSetterBiConsumers.put(
			"plano_id", (BiConsumer<PlanoSaude, Long>)PlanoSaude::setPlano_id);
		attributeGetterFunctions.put("descricao", PlanoSaude::getDescricao);
		attributeSetterBiConsumers.put(
			"descricao",
			(BiConsumer<PlanoSaude, String>)PlanoSaude::setDescricao);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getPlano_id() {
		return _plano_id;
	}

	@Override
	public void setPlano_id(long plano_id) {
		_plano_id = plano_id;
	}

	@Override
	public String getDescricao() {
		if (_descricao == null) {
			return "";
		}
		else {
			return _descricao;
		}
	}

	@Override
	public void setDescricao(String descricao) {
		_columnBitmask |= DESCRICAO_COLUMN_BITMASK;

		if (_originalDescricao == null) {
			_originalDescricao = _descricao;
		}

		_descricao = descricao;
	}

	public String getOriginalDescricao() {
		return GetterUtil.getString(_originalDescricao);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, PlanoSaude.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PlanoSaude toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PlanoSaude>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PlanoSaudeImpl planoSaudeImpl = new PlanoSaudeImpl();

		planoSaudeImpl.setPlano_id(getPlano_id());
		planoSaudeImpl.setDescricao(getDescricao());

		planoSaudeImpl.resetOriginalValues();

		return planoSaudeImpl;
	}

	@Override
	public int compareTo(PlanoSaude planoSaude) {
		long primaryKey = planoSaude.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PlanoSaude)) {
			return false;
		}

		PlanoSaude planoSaude = (PlanoSaude)obj;

		long primaryKey = planoSaude.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		PlanoSaudeModelImpl planoSaudeModelImpl = this;

		planoSaudeModelImpl._originalDescricao = planoSaudeModelImpl._descricao;

		planoSaudeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PlanoSaude> toCacheModel() {
		PlanoSaudeCacheModel planoSaudeCacheModel = new PlanoSaudeCacheModel();

		planoSaudeCacheModel.plano_id = getPlano_id();

		planoSaudeCacheModel.descricao = getDescricao();

		String descricao = planoSaudeCacheModel.descricao;

		if ((descricao != null) && (descricao.length() == 0)) {
			planoSaudeCacheModel.descricao = null;
		}

		return planoSaudeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PlanoSaude, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PlanoSaude, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PlanoSaude, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((PlanoSaude)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PlanoSaude, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PlanoSaude, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PlanoSaude, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PlanoSaude)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PlanoSaude>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _plano_id;
	private String _descricao;
	private String _originalDescricao;
	private long _columnBitmask;
	private PlanoSaude _escapedModel;

}